/**
 * JobMatching
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Candidate } from './candidate';
import { Job } from './job';


export interface JobCandidate { 
    job?: Job;
    matchedCandidate?: Candidate;
    match?: boolean;
    tagMatched?: number;
}

